apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: output
  steps:
    - name: remove
      image: alpine:3
      script: |
        #!/bin/sh
        rm -rf $(workspaces.output.path)/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
      description: The git repository URL to clone
  workspaces:
    - name: output
  steps:
    - name: clone
      image: alpine/git
      script: |
        git clone $(params.url) $(workspaces.output.path)

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: flake8
spec:
  workspaces:
    - name: output
  steps:
    - name: lint
      image: python:3.8
      workingDir: $(workspaces.output.path)
      script: |
        pip install flake8
        flake8 .

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose
spec:
  workspaces:
    - name: output
  steps:
    - name: test
      image: python:3.8
      workingDir: $(workspaces.output.path)
      script: |
        pip install nose
        nosetests

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: buildah
spec:
  workspaces:
    - name: output
  steps:
    - name: build
      image: quay.io/buildah/stable
      workingDir: $(workspaces.output.path)
      script: |
        buildah bud -t my-image:latest .

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-app
spec:
  workspaces:
    - name: output
  steps:
    - name: deploy
      image: bitnami/kubectl
      script: |
        kubectl apply -f deployment.yaml